"""Prompt templates for VLMgineer."""

from .system import INITIAL_MISSION_PROMPT, EVOLUTION_MISSION_PROMPT, PROCEDURE_PROMPT
from .tool_spec import TOOL_SPECIFICATION_PROMPT, TOOL_SPECIFICATION_WITH_GRIPPER_PROMPT
from .action_spec import (
    ACTION_SPECIFICATION_PROMPT, 
    ACTION_DIVERSITY_PROMPT,
    FRAME_CLARIFICATION_PROMPT
)
from .evolution import EVOLUTION_INSTRUCTION_PROMPT, SELECTION_CRITERIA_PROMPT

__all__ = [
    "INITIAL_MISSION_PROMPT",
    "EVOLUTION_MISSION_PROMPT",
    "PROCEDURE_PROMPT",
    "TOOL_SPECIFICATION_PROMPT",
    "TOOL_SPECIFICATION_WITH_GRIPPER_PROMPT",
    "ACTION_SPECIFICATION_PROMPT",
    "ACTION_DIVERSITY_PROMPT",
    "FRAME_CLARIFICATION_PROMPT",
    "EVOLUTION_INSTRUCTION_PROMPT",
    "SELECTION_CRITERIA_PROMPT",
]
